---
- hosts: all
  gather_facts: no

  vars:
    appname: tgcw

  tasks:
  - name: Delete src directory from host
    file:
      path: /{{appname}}
      state: absent

  - name: Copy src to host
    copy:
      src: ../app
      dest: /{{appname}}

  - name: Delete old image
    docker_image:
      name: "{{appname}}-image"
      state: absent
      force: yes

  - name: Build new image
    docker_image:
      path: /{{appname}}/app
      name: "{{appname}}-image"

  - name: Run container
    docker_container:
      name: "{{appname}}"
      image: "{{appname}}-image"
      state: started
      recreate: yes
      restart_policy: on-failure
